version: 2.1

orbs:
  python: circleci/python@0.2.1

commands:

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install poetry
          command: pip install poetry
      - run:
          name: Build sdist
          command: poetry build

workflows:
  main:
    jobs:
      - build-and-test
