version: 2.1

orbs:
  python: circleci/python@0.2.1

commands:

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install poetry
          command: pip install poetry
      - run:
          name: Build sdist
          command: poetry build
  test:
    docker:
      - image: redislabs/redisgears:1.2.5
    steps:
      - checkout

      - run:
          name: install tox dependencies
          command: |
            /var/opt/redislabs/modules/rg/python3_99.99.99/bin/python3 -m pip install --upgrade pip virtualenv
            /var/opt/redislabs/modules/rg/python3_99.99.99/bin/python3 -m pip install -r .circleci/circle_requirements.txt
      - run:
          name: build sdist and wheels
          command: |
            /var/opt/redislabs/modules/rg/python3_99.99.99/bin/python3 -m poetry build
      - run:
          name: run tests
          command:
            /var/opt/redislabs/modules/rg/python3_99.99.99/bin/python3 -m tox -e tests

workflows:
  main:
    jobs:
      - build
      - test
